# FluxDown Windows GPUI workspace

[workspace]
resolver = "3"
members = [
  "native/engine",
  "native/engine-protocol",
  "native/protocol",
  "native/api",
  "native/daemon",
  "native/agent",
  "native/nmh",
  "native/fluxdown_updater",
  "crates/*",
  "scripts/desktop-dev",
]

[workspace.package]
edition = "2024"

[workspace.dependencies]
gpui = { version = "0.2.2", git = "https://github.com/zed-industries/zed" }
gpui_platform = { git = "https://github.com/zed-industries/zed" }
gpui-base = { git = "https://github.com/longbridge/gpui-component", rev = "334bbed2e8c47d606eb79ab05ddcebd60b823429" }
gpui-component = { git = "https://github.com/longbridge/gpui-component", rev = "334bbed2e8c47d606eb79ab05ddcebd60b823429" }
gpui-component-assets = { git = "https://github.com/longbridge/gpui-component", rev = "334bbed2e8c47d606eb79ab05ddcebd60b823429" }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1"
thiserror = "2.0"
winresource = "0.1.31"

[workspace.lints.clippy]
expect_used = "deny"
unwrap_used = "deny"
wildcard_imports = "deny"

[patch.crates-io]
librqbit = { git = "https://github.com/lingdiansr/rqbit", rev = "3860dbe08c0b11efc0d8499de128b5a18195c44d" }

[profile.dev]
codegen-units = 16
debug = "limited"
split-debuginfo = "unpacked"

[profile.dev.package.gpui]
opt-level = 3

[profile.dev.package.gpui_platform]
opt-level = 3

[profile.release]
strip = true
opt-level = "z"
lto = "fat"
codegen-units = 1
